### ISSUE TITLE
Clock shows Tuesday on Monday 😖

### ISSUE THREAD

**Issue by alhockly** [conorhennessy/php-Boy#1]
Plz fix

**Comment by conorhennessy** [comment]
Thank you for reporting this error, I have passed it onto the relevant team for a fix!

Thank you for being a keen supporter of our project!

**Comment by conorhennessy** [comment]
fix works locally on my device but not on the device...

**Comment by conorhennessy** [comment]
Latest commit was to add a line above clock to prove that day calculation is working

**Comment by conorhennessy** [comment]
Seems like this is fixed with latest clock commit, will wait to see for a full week if days are working!
