### ISSUE TITLE
Chromium freezes when running for a long period of time

### ISSUE THREAD

**Issue by alhockly** [conorhennessy/php-Boy#2]
The clock was stopped at 12:00:01pm
chromium locked right up; no F5, no Ctrl+W, no nada and this is happened two days in a row (except the first time I think it was 12:00:00 (hmmmmm))

**Comment by conorhennessy** [comment]
Ok.
To try and figure out what is causing logging can be turned on by launching chrome with the command:  
  `--enable-logging --v=1` and the logs can then be viewed at `chrome://crashes` .

Guides I'm using: 
[Chromium - enable logging](https://www.chromium.org/for-testers/enable-logging)
[StackOverflow - where to find logs](https://stackoverflow.com/questions/12740440/where-to-find-google-chrome-logs)

**Comment by alhockly** [comment]
Ahh sweet
